unique_ids:
  forms:
    Form1: ID4VENLUIPEVU7DO7HOJJ6YUBVO4KWMA
  modules: {}
  server_modules: {}
  assets:
    theme.css: MRRRPZ2ISZ25FB5UGGY6I3CRB7XY2EO6
    standard-page.html: X6QUAIYNVIDTWWFJFC2VVSHUNZ5S6UJ4
  scripts: {}
